// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC29iKSauMe7zLT7O75iwbuo7ooUZTP80w',
    appId: '1:78700636267:web:692cb9b66643e9d0a4292e',
    messagingSenderId: '78700636267',
    projectId: 'aissign',
    authDomain: 'aissign.firebaseapp.com',
    storageBucket: 'aissign.firebasestorage.app',
    measurementId: 'G-2YTT4QBZLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQPev3PqzSYIlQGzrFraw5_qqHs6me-g',
    appId: '1:78700636267:android:beafdecacfc87673a4292e',
    messagingSenderId: '78700636267',
    projectId: 'aissign',
    storageBucket: 'aissign.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpFpPUEVh0NwiPQXscfWXh4WmM5okqHzU',
    appId: '1:78700636267:ios:ca11ba5ec0e36493a4292e',
    messagingSenderId: '78700636267',
    projectId: 'aissign',
    storageBucket: 'aissign.firebasestorage.app',
    iosBundleId: 'com.example.aipm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpFpPUEVh0NwiPQXscfWXh4WmM5okqHzU',
    appId: '1:78700636267:ios:ca11ba5ec0e36493a4292e',
    messagingSenderId: '78700636267',
    projectId: 'aissign',
    storageBucket: 'aissign.firebasestorage.app',
    iosBundleId: 'com.example.aipm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC29iKSauMe7zLT7O75iwbuo7ooUZTP80w',
    appId: '1:78700636267:web:7d0f9db2497c2e1ba4292e',
    messagingSenderId: '78700636267',
    projectId: 'aissign',
    authDomain: 'aissign.firebaseapp.com',
    storageBucket: 'aissign.firebasestorage.app',
    measurementId: 'G-J0Y1897R6S',
  );
}
